In [33]:
import numpy as np

In [3]:
a=np.array([1,2.1,3])

In [4]:
action = np.where(a > 3)

In [5]:
print(action)

(array([], dtype=int64),)


In [6]:
np.shape(action)

(1, 0)

In [7]:
a[action]

array([], dtype=float64)

In [8]:
np.random.rand(1)[0]

0.934411173091282

In [9]:
1/4

0.25

In [10]:
type(np.infty)

float

In [11]:
def UCB_help(reward, n_total, n_action):
    reward = 2

In [12]:
UCB_help(a, 3, a)

In [13]:
a

array([1. , 2.1, 3. ])

In [14]:
action = np.random.randint(7)

In [15]:
np.amax(a)

3.0

In [16]:
b=np.ones([2,3])

In [17]:
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
np.array([1,2,3])+np.array(4)

array([5, 6, 7])

In [20]:
b.mean(axis=0)

array([1., 1., 1.])

In [23]:
np.zeros([2,])

array([0., 0.])

In [32]:
list(range(10,-1,-1))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [34]:
a=np.array([[1,2],[1,4],[2,5]])

In [36]:
np.sum(a,axis = 1)

array([3, 5, 7])

In [40]:
np.random.randint(2)

0

In [43]:
np.mean(a,axis=1)

array([1.5, 2.5, 3.5])

In [44]:
for i in range(100,-1,-1):
    print(i)

100
99
98
97
96
95
94
93
92
91
90
89
88
87
86
85
84
83
82
81
80
79
78
77
76
75
74
73
72
71
70
69
68
67
66
65
64
63
62
61
60
59
58
57
56
55
54
53
52
51
50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1
0
