In [2]:
import numpy as np

In [3]:
a=np.array([1,2.1,3])

In [4]:
action = np.where(a > 3)

In [5]:
print(action)

(array([], dtype=int64),)


In [6]:
np.shape(action)

(1, 0)

In [7]:
a[action]

array([], dtype=float64)

In [8]:
np.random.rand(1)[0]

0.934411173091282

In [9]:
1/4

0.25

In [10]:
type(np.infty)

float

In [11]:
def UCB_help(reward, n_total, n_action):
    reward = 2

In [12]:
UCB_help(a, 3, a)

In [13]:
a

array([1. , 2.1, 3. ])

In [14]:
action = np.random.randint(7)

In [15]:
np.amax(a)

3.0

In [16]:
b=np.ones([2,3])

In [17]:
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
np.array([1,2,3])+np.array(4)

array([5, 6, 7])

In [20]:
b.mean(axis=0)

array([1., 1., 1.])

In [23]:
np.zeros([2,])

array([0., 0.])

In [32]:
list(range(10,-1,-1))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]